module.exports = {
  apps: [
    {
      name: 'react-dev',
      script: './apps/frontend/node_modules/.bin/vite',
      args: '--host 0.0.0.0 --port 3000',
      cwd: './apps/frontend',
      interpreter: 'node',
      env: {
        NODE_ENV: 'development',
      },
      error_file: './logs/react-dev-error.log',
      out_file: './logs/react-dev-out.log',
      log_file: './logs/react-dev-combined.log',
      time: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
    },
    {
      name: 'react-ssr-dev',
      script: './apps/frontend/node_modules/.bin/tsx',
      args: 'server/index.ts',
      cwd: './apps/frontend',
      interpreter: 'node',
      env: {
        NODE_ENV: 'development',
        PORT: 3000,
        BASE_PATH: '/',
      },
      error_file: './logs/react-ssr-dev-error.log',
      out_file: './logs/react-ssr-dev-out.log',
      log_file: './logs/react-ssr-dev-combined.log',
      time: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
    },
    {
      name: 'react-ssr-prod',
      script: './apps/frontend/dist/server/index.js',
      cwd: './apps/frontend',
      interpreter: 'node',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        BASE_PATH: '/',
      },
      error_file: './logs/react-ssr-prod-error.log',
      out_file: './logs/react-ssr-prod-out.log',
      log_file: './logs/react-ssr-prod-combined.log',
      time: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      instances: 2,
      exec_mode: 'cluster',
    },
  ],
};
