import {
  Archive,
  Armchair,
  ArrowLeftRight,
  ArrowRight,
  ArrowUpFromLine,
  Award,
  Baby,
  BedDouble,
  Bell,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  Calculator,
  Calendar,
  Car,
  ChartLine,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleCheck,
  CircleDollarSign,
  CircleHelp,
  CircleX,
  ClipboardList,
  Clock,
  CloudUpload,
  Copy,
  CreditCard,
  DoorOpen,
  Download,
  Eye,
  FileChartColumn,
  FilePlus,
  FileText,
  Gift,
  GraduationCap,
  Hammer,
  Headset,
  Heart,
  House,
  ImageIcon,
  Info,
  Layers,
  Leaf,
  Lightbulb,
  ListChecks,
  ListFilter,
  LoaderCircle,
  Lock,
  LogOut,
  Mail,
  MailCheck,
  MapPin,
  Megaphone,
  MenuIcon,
  MessageCircle,
  MessageSquare,
  Minus,
  Package,
  Palette,
  Paperclip,
  Pencil,
  Phone,
  Plug,
  Plus,
  Save,
  Search,
  Send,
  Settings,
  Share2,
  ShieldCheck,
  Ship,
  ShoppingBag,
  ShoppingCart,
  Smile,
  Snowflake,
  Sofa,
  Star,
  Store,
  Sun,
  TableIcon,
  Tag,
  ThermometerSun,
  TrainFront,
  Trash2,
  TriangleAlert,
  Trophy,
  Truck,
  Tv,
  Undo2,
  User,
  UserPlus,
  Users,
  Utensils,
  Wrench,
  X,
  Zap,
  ZoomIn,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

/**
 * Канонические идентификаторы Lucide, которые разрешено хранить в backend.
 *
 * Backend мигрирует старые Remixicon-значения и валидирует новые записи,
 * поэтому фронт больше не содержит отдельный compatibility-слой Remixicon.
 * Ключи этого словаря совпадают со slug'ами App\Support\LucideIconRegistry.
 */
export const LUCIDE_ICONS: Record<string, LucideIcon> = {
  archive: Archive,
  armchair: Armchair,
  'arrow-left-right': ArrowLeftRight,
  'arrow-right': ArrowRight,
  'arrow-up-from-line': ArrowUpFromLine,
  award: Award,
  baby: Baby,
  'bed-double': BedDouble,
  bell: Bell,
  'book-open': BookOpen,
  briefcase: Briefcase,
  'building-2': Building2,
  bus: Bus,
  calculator: Calculator,
  calendar: Calendar,
  car: Car,
  'chart-line': ChartLine,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'circle-check': CircleCheck,
  'circle-dollar-sign': CircleDollarSign,
  'circle-help': CircleHelp,
  'circle-x': CircleX,
  'clipboard-list': ClipboardList,
  clock: Clock,
  'cloud-upload': CloudUpload,
  copy: Copy,
  'credit-card': CreditCard,
  'door-open': DoorOpen,
  download: Download,
  eye: Eye,
  'file-chart-column': FileChartColumn,
  'file-plus': FilePlus,
  'file-text': FileText,
  gift: Gift,
  'graduation-cap': GraduationCap,
  hammer: Hammer,
  headset: Headset,
  heart: Heart,
  house: House,
  image: ImageIcon,
  info: Info,
  layers: Layers,
  leaf: Leaf,
  lightbulb: Lightbulb,
  'list-checks': ListChecks,
  'list-filter': ListFilter,
  'loader-circle': LoaderCircle,
  lock: Lock,
  'log-out': LogOut,
  mail: Mail,
  'mail-check': MailCheck,
  'map-pin': MapPin,
  megaphone: Megaphone,
  menu: MenuIcon,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  minus: Minus,
  package: Package,
  palette: Palette,
  paperclip: Paperclip,
  pencil: Pencil,
  phone: Phone,
  plug: Plug,
  plus: Plus,
  save: Save,
  search: Search,
  send: Send,
  settings: Settings,
  'share-2': Share2,
  'shield-check': ShieldCheck,
  ship: Ship,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  smile: Smile,
  snowflake: Snowflake,
  sofa: Sofa,
  star: Star,
  store: Store,
  sun: Sun,
  table: TableIcon,
  tag: Tag,
  'thermometer-sun': ThermometerSun,
  'train-front': TrainFront,
  'trash-2': Trash2,
  'triangle-alert': TriangleAlert,
  trophy: Trophy,
  truck: Truck,
  tv: Tv,
  'undo-2': Undo2,
  user: User,
  'user-plus': UserPlus,
  users: Users,
  utensils: Utensils,
  wrench: Wrench,
  x: X,
  zap: Zap,
  'zoom-in': ZoomIn,
};

export interface ResolvedIcon {
  icon: LucideIcon;
  /**
   * Сохраняем shape результата для обратной совместимости компонента Icon.
   * Для канонических Lucide-slug заливка не кодируется в имени.
   */
  filled: false;
}

export function resolveIcon(name: string): ResolvedIcon | null {
  const icon: LucideIcon | undefined = LUCIDE_ICONS[name];
  return icon ? { icon, filled: false } : null;
}
