import {
  Archive,
  Armchair,
  ArrowLeftRight,
  ArrowRight,
  ArrowUpFromLine,
  Award,
  Baby,
  BedDouble,
  Bell,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  Calculator,
  Calendar,
  Car,
  ChartLine,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleCheck,
  CircleDollarSign,
  CircleHelp,
  CircleX,
  ClipboardList,
  Clock,
  CloudUpload,
  Copy,
  CreditCard,
  DoorOpen,
  Download,
  Eye,
  FileChartColumn,
  FilePlus,
  FileText,
  Gift,
  GraduationCap,
  Hammer,
  Headset,
  Heart,
  House,
  ImageIcon,
  Info,
  Layers,
  Leaf,
  Lightbulb,
  ListChecks,
  ListFilter,
  LoaderCircle,
  Lock,
  LogOut,
  Mail,
  MailCheck,
  MapPin,
  Megaphone,
  MenuIcon,
  MessageCircle,
  MessageSquare,
  Minus,
  Package,
  Palette,
  Paperclip,
  Pencil,
  Phone,
  Plug,
  Plus,
  Save,
  Search,
  Send,
  Settings,
  Share2,
  ShieldCheck,
  Ship,
  ShoppingBag,
  ShoppingCart,
  Smile,
  Snowflake,
  Sofa,
  Star,
  Store,
  Sun,
  TableIcon,
  Tag,
  ThermometerSun,
  TrainFront,
  Trash2,
  TriangleAlert,
  Trophy,
  Truck,
  Tv,
  Undo2,
  User,
  UserPlus,
  Users,
  Utensils,
  Wrench,
  X,
  Zap,
  ZoomIn,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

/**
 * Соответствие имён Remixicon компонентам Lucide.
 *
 * Нужно потому, что имена иконок приходят с бэкенда: категории каталога,
 * способы оплаты, услуги, блоки товара, бейдж слайдера. В базе лежат строки
 * вида `ri-truck-line`, их выбирает администратор в Filament. Пока это так,
 * фронт обязан их понимать.
 *
 * Ключи без суффикса: `-line` и `-fill` отбрасываются при разборе, потому что
 * у Lucide это один и тот же контур, залитый или нет.
 *
 * Когда бэкенд перейдёт на имена Lucide, карта станет не нужна — компонент
 * Icon принимает и строку, и готовый компонент.
 */
export const LEGACY_ICONS: Record<string, LucideIcon> = {
  'ri-add': Plus,
  'ri-advertisement': Megaphone,
  'ri-archive': Archive,
  'ri-armchair': Armchair,
  'ri-arrow-down-s': ChevronDown,
  'ri-arrow-go-back': Undo2,
  'ri-arrow-left-s': ChevronLeft,
  'ri-arrow-right': ArrowRight,
  'ri-arrow-right-s': ChevronRight,
  'ri-attachment-2': Paperclip,
  'ri-award': Award,
  'ri-bank-card': CreditCard,
  'ri-bear-smile': Baby,
  'ri-book': BookOpen,
  'ri-box-3': Package, // Упаковка в коробки
  'ri-briefcase': Briefcase,
  'ri-building': Building2,
  'ri-bus': Bus,
  'ri-calculator': Calculator,
  'ri-calendar': Calendar,
  'ri-car': Car,
  'ri-chat-3': MessageCircle,
  'ri-check': Check,
  'ri-checkbox-circle': CircleCheck,
  'ri-close': X,
  'ri-close-circle': CircleX,
  'ri-customer-service': Headset,
  'ri-customer-service-2': Headset,
  'ri-delete-bin': Trash2,
  'ri-door': DoorOpen,
  'ri-download': Download,
  'ri-edit': Pencil,
  'ri-error-warning': TriangleAlert,
  'ri-exchange': ArrowLeftRight,
  'ri-eye': Eye,
  'ri-file-add': FilePlus,
  'ri-file-chart': FileChartColumn,
  'ri-file-copy': Copy,
  'ri-file-list-3': ClipboardList,
  'ri-file-text': FileText,
  'ri-filter-3': ListFilter,
  'ri-flashlight': Zap,
  'ri-gift': Gift,
  'ri-graduation-cap': GraduationCap,
  'ri-hammer': Hammer, // Демонтаж старой мебели
  'ri-heart': Heart,
  'ri-home': House,
  'ri-hotel-bed': BedDouble,
  'ri-image': ImageIcon,
  'ri-information': Info,
  'ri-install': Plug, // Установка техники
  'ri-leaf': Leaf, // Экологичность
  'ri-lightbulb': Lightbulb,
  'ri-line-chart': ChartLine,
  'ri-list-check': ListChecks,
  'ri-loader-4': LoaderCircle,
  'ri-lock-password': Lock,
  'ri-logout-box': LogOut,
  'ri-mail': Mail,
  'ri-mail-send': MailCheck,
  'ri-map-pin': MapPin,
  'ri-map-pin-2': MapPin,
  'ri-map-pin-3': MapPin,
  'ri-menu': MenuIcon,
  'ri-message-3': MessageSquare,
  'ri-money-dollar-circle': CircleDollarSign,
  'ri-notification': Bell,
  'ri-palette': Palette,
  'ri-phone': Phone,
  'ri-price-tag-3': Tag,
  'ri-question': CircleHelp,
  'ri-restaurant': Utensils,
  'ri-save': Save,
  'ri-scales-3': ArrowLeftRight,
  'ri-search': Search,
  'ri-send-plane': Send,
  'ri-settings': Settings,
  'ri-settings-3': Settings,
  'ri-share': Share2,
  'ri-shield-check': ShieldCheck,
  'ri-ship': Ship,
  'ri-shopping-bag': ShoppingBag,
  'ri-shopping-cart': ShoppingCart,
  'ri-snowy': Snowflake,
  'ri-sofa': Sofa,
  'ri-stackshare': Layers,
  'ri-stairs': ArrowUpFromLine, // Подъем на этаж
  'ri-star': Star,
  'ri-store': Store,
  'ri-subtract': Minus,
  'ri-subway': TrainFront,
  'ri-sun': Sun,
  'ri-table': TableIcon,
  'ri-team': Users,
  'ri-temp-hot': ThermometerSun,
  'ri-time': Clock,
  'ri-tools': Wrench,
  'ri-trophy': Trophy, // достижения
  'ri-truck': Truck,
  'ri-tv': Tv,
  'ri-upload-cloud': CloudUpload,
  'ri-user': User,
  'ri-user-add': UserPlus,
  'ri-user-smile': Smile,
  'ri-zoom-in': ZoomIn,
};

export interface ResolvedIcon {
  icon: LucideIcon;
  /** У Remixicon вариант `-fill` был отдельным рисунком, у Lucide это заливка контура. */
  filled: boolean;
}

export function resolveIcon(name: string): ResolvedIcon | null {
  const filled = name.endsWith('-fill');
  const base = name.replace(/-(line|fill)$/, '');
  // Индексация Record даёт неопционально типизированное значение,
  // поэтому сужаем вручную: ключа может не быть.
  const icon: LucideIcon | undefined = LEGACY_ICONS[base];
  return icon ? { icon, filled } : null;
}
